# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stradivarius/Desktop/impro/IMprovEEsation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stradivarius/Desktop/impro/IMprovEEsation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stradivarius/Desktop/impro/IMprovEEsation/CMakeFiles /home/stradivarius/Desktop/impro/IMprovEEsation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stradivarius/Desktop/impro/IMprovEEsation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named db_test

# Build rule for target.
db_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_test
.PHONY : db_test

# fast build rule for target.
db_test/fast:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/build
.PHONY : db_test/fast

#=============================================================================
# Target rules for targets named director

# Build rule for target.
director: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 director
.PHONY : director

# fast build rule for target.
director/fast:
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/build
.PHONY : director/fast

#=============================================================================
# Target rules for targets named improveesation_communication

# Build rule for target.
improveesation_communication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 improveesation_communication
.PHONY : improveesation_communication

# fast build rule for target.
improveesation_communication/fast:
	$(MAKE) -f CMakeFiles/improveesation_communication.dir/build.make CMakeFiles/improveesation_communication.dir/build
.PHONY : improveesation_communication/fast

#=============================================================================
# Target rules for targets named improveesation_db

# Build rule for target.
improveesation_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 improveesation_db
.PHONY : improveesation_db

# fast build rule for target.
improveesation_db/fast:
	$(MAKE) -f CMakeFiles/improveesation_db.dir/build.make CMakeFiles/improveesation_db.dir/build
.PHONY : improveesation_db/fast

#=============================================================================
# Target rules for targets named musician

# Build rule for target.
musician: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 musician
.PHONY : musician

# fast build rule for target.
musician/fast:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/build
.PHONY : musician/fast

#=============================================================================
# Target rules for targets named player

# Build rule for target.
player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 player
.PHONY : player

# fast build rule for target.
player/fast:
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/build
.PHONY : player/fast

#=============================================================================
# Target rules for targets named resetdb

# Build rule for target.
resetdb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resetdb
.PHONY : resetdb

# fast build rule for target.
resetdb/fast:
	$(MAKE) -f CMakeFiles/resetdb.dir/build.make CMakeFiles/resetdb.dir/build
.PHONY : resetdb/fast

core/communication.o: core/communication.cpp.o
.PHONY : core/communication.o

# target to build an object file
core/communication.cpp.o:
	$(MAKE) -f CMakeFiles/improveesation_communication.dir/build.make CMakeFiles/improveesation_communication.dir/core/communication.cpp.o
.PHONY : core/communication.cpp.o

core/communication.i: core/communication.cpp.i
.PHONY : core/communication.i

# target to preprocess a source file
core/communication.cpp.i:
	$(MAKE) -f CMakeFiles/improveesation_communication.dir/build.make CMakeFiles/improveesation_communication.dir/core/communication.cpp.i
.PHONY : core/communication.cpp.i

core/communication.s: core/communication.cpp.s
.PHONY : core/communication.s

# target to generate assembly for a file
core/communication.cpp.s:
	$(MAKE) -f CMakeFiles/improveesation_communication.dir/build.make CMakeFiles/improveesation_communication.dir/core/communication.cpp.s
.PHONY : core/communication.cpp.s

core/configuration.o: core/configuration.cpp.o
.PHONY : core/configuration.o

# target to build an object file
core/configuration.cpp.o:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/configuration.cpp.o
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/configuration.cpp.o
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/configuration.cpp.o
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/configuration.cpp.o
.PHONY : core/configuration.cpp.o

core/configuration.i: core/configuration.cpp.i
.PHONY : core/configuration.i

# target to preprocess a source file
core/configuration.cpp.i:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/configuration.cpp.i
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/configuration.cpp.i
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/configuration.cpp.i
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/configuration.cpp.i
.PHONY : core/configuration.cpp.i

core/configuration.s: core/configuration.cpp.s
.PHONY : core/configuration.s

# target to generate assembly for a file
core/configuration.cpp.s:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/configuration.cpp.s
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/configuration.cpp.s
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/configuration.cpp.s
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/configuration.cpp.s
.PHONY : core/configuration.cpp.s

core/db.o: core/db.cpp.o
.PHONY : core/db.o

# target to build an object file
core/db.cpp.o:
	$(MAKE) -f CMakeFiles/improveesation_db.dir/build.make CMakeFiles/improveesation_db.dir/core/db.cpp.o
.PHONY : core/db.cpp.o

core/db.i: core/db.cpp.i
.PHONY : core/db.i

# target to preprocess a source file
core/db.cpp.i:
	$(MAKE) -f CMakeFiles/improveesation_db.dir/build.make CMakeFiles/improveesation_db.dir/core/db.cpp.i
.PHONY : core/db.cpp.i

core/db.s: core/db.cpp.s
.PHONY : core/db.s

# target to generate assembly for a file
core/db.cpp.s:
	$(MAKE) -f CMakeFiles/improveesation_db.dir/build.make CMakeFiles/improveesation_db.dir/core/db.cpp.s
.PHONY : core/db.cpp.s

core/db_library_test.o: core/db_library_test.cpp.o
.PHONY : core/db_library_test.o

# target to build an object file
core/db_library_test.cpp.o:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/db_library_test.cpp.o
.PHONY : core/db_library_test.cpp.o

core/db_library_test.i: core/db_library_test.cpp.i
.PHONY : core/db_library_test.i

# target to preprocess a source file
core/db_library_test.cpp.i:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/db_library_test.cpp.i
.PHONY : core/db_library_test.cpp.i

core/db_library_test.s: core/db_library_test.cpp.s
.PHONY : core/db_library_test.s

# target to generate assembly for a file
core/db_library_test.cpp.s:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/db_library_test.cpp.s
.PHONY : core/db_library_test.cpp.s

core/director_core.o: core/director_core.cpp.o
.PHONY : core/director_core.o

# target to build an object file
core/director_core.cpp.o:
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/director_core.cpp.o
.PHONY : core/director_core.cpp.o

core/director_core.i: core/director_core.cpp.i
.PHONY : core/director_core.i

# target to preprocess a source file
core/director_core.cpp.i:
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/director_core.cpp.i
.PHONY : core/director_core.cpp.i

core/director_core.s: core/director_core.cpp.s
.PHONY : core/director_core.s

# target to generate assembly for a file
core/director_core.cpp.s:
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/director_core.cpp.s
.PHONY : core/director_core.cpp.s

core/director_main.o: core/director_main.cpp.o
.PHONY : core/director_main.o

# target to build an object file
core/director_main.cpp.o:
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/director_main.cpp.o
.PHONY : core/director_main.cpp.o

core/director_main.i: core/director_main.cpp.i
.PHONY : core/director_main.i

# target to preprocess a source file
core/director_main.cpp.i:
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/director_main.cpp.i
.PHONY : core/director_main.cpp.i

core/director_main.s: core/director_main.cpp.s
.PHONY : core/director_main.s

# target to generate assembly for a file
core/director_main.cpp.s:
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/director_main.cpp.s
.PHONY : core/director_main.cpp.s

core/musician_core.o: core/musician_core.cpp.o
.PHONY : core/musician_core.o

# target to build an object file
core/musician_core.cpp.o:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_core.cpp.o
.PHONY : core/musician_core.cpp.o

core/musician_core.i: core/musician_core.cpp.i
.PHONY : core/musician_core.i

# target to preprocess a source file
core/musician_core.cpp.i:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_core.cpp.i
.PHONY : core/musician_core.cpp.i

core/musician_core.s: core/musician_core.cpp.s
.PHONY : core/musician_core.s

# target to generate assembly for a file
core/musician_core.cpp.s:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_core.cpp.s
.PHONY : core/musician_core.cpp.s

core/musician_improviser.o: core/musician_improviser.cpp.o
.PHONY : core/musician_improviser.o

# target to build an object file
core/musician_improviser.cpp.o:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_improviser.cpp.o
.PHONY : core/musician_improviser.cpp.o

core/musician_improviser.i: core/musician_improviser.cpp.i
.PHONY : core/musician_improviser.i

# target to preprocess a source file
core/musician_improviser.cpp.i:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_improviser.cpp.i
.PHONY : core/musician_improviser.cpp.i

core/musician_improviser.s: core/musician_improviser.cpp.s
.PHONY : core/musician_improviser.s

# target to generate assembly for a file
core/musician_improviser.cpp.s:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_improviser.cpp.s
.PHONY : core/musician_improviser.cpp.s

core/musician_main.o: core/musician_main.cpp.o
.PHONY : core/musician_main.o

# target to build an object file
core/musician_main.cpp.o:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_main.cpp.o
.PHONY : core/musician_main.cpp.o

core/musician_main.i: core/musician_main.cpp.i
.PHONY : core/musician_main.i

# target to preprocess a source file
core/musician_main.cpp.i:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_main.cpp.i
.PHONY : core/musician_main.cpp.i

core/musician_main.s: core/musician_main.cpp.s
.PHONY : core/musician_main.s

# target to generate assembly for a file
core/musician_main.cpp.s:
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/musician_main.cpp.s
.PHONY : core/musician_main.cpp.s

core/player_core.o: core/player_core.cpp.o
.PHONY : core/player_core.o

# target to build an object file
core/player_core.cpp.o:
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/player_core.cpp.o
.PHONY : core/player_core.cpp.o

core/player_core.i: core/player_core.cpp.i
.PHONY : core/player_core.i

# target to preprocess a source file
core/player_core.cpp.i:
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/player_core.cpp.i
.PHONY : core/player_core.cpp.i

core/player_core.s: core/player_core.cpp.s
.PHONY : core/player_core.s

# target to generate assembly for a file
core/player_core.cpp.s:
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/player_core.cpp.s
.PHONY : core/player_core.cpp.s

core/player_main.o: core/player_main.cpp.o
.PHONY : core/player_main.o

# target to build an object file
core/player_main.cpp.o:
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/player_main.cpp.o
.PHONY : core/player_main.cpp.o

core/player_main.i: core/player_main.cpp.i
.PHONY : core/player_main.i

# target to preprocess a source file
core/player_main.cpp.i:
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/player_main.cpp.i
.PHONY : core/player_main.cpp.i

core/player_main.s: core/player_main.cpp.s
.PHONY : core/player_main.s

# target to generate assembly for a file
core/player_main.cpp.s:
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/player_main.cpp.s
.PHONY : core/player_main.cpp.s

core/utils.o: core/utils.cpp.o
.PHONY : core/utils.o

# target to build an object file
core/utils.cpp.o:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/utils.cpp.o
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/utils.cpp.o
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/utils.cpp.o
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/utils.cpp.o
.PHONY : core/utils.cpp.o

core/utils.i: core/utils.cpp.i
.PHONY : core/utils.i

# target to preprocess a source file
core/utils.cpp.i:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/utils.cpp.i
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/utils.cpp.i
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/utils.cpp.i
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/utils.cpp.i
.PHONY : core/utils.cpp.i

core/utils.s: core/utils.cpp.s
.PHONY : core/utils.s

# target to generate assembly for a file
core/utils.cpp.s:
	$(MAKE) -f CMakeFiles/db_test.dir/build.make CMakeFiles/db_test.dir/core/utils.cpp.s
	$(MAKE) -f CMakeFiles/director.dir/build.make CMakeFiles/director.dir/core/utils.cpp.s
	$(MAKE) -f CMakeFiles/musician.dir/build.make CMakeFiles/musician.dir/core/utils.cpp.s
	$(MAKE) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/core/utils.cpp.s
.PHONY : core/utils.cpp.s

tools/resetdb.o: tools/resetdb.c.o
.PHONY : tools/resetdb.o

# target to build an object file
tools/resetdb.c.o:
	$(MAKE) -f CMakeFiles/resetdb.dir/build.make CMakeFiles/resetdb.dir/tools/resetdb.c.o
.PHONY : tools/resetdb.c.o

tools/resetdb.i: tools/resetdb.c.i
.PHONY : tools/resetdb.i

# target to preprocess a source file
tools/resetdb.c.i:
	$(MAKE) -f CMakeFiles/resetdb.dir/build.make CMakeFiles/resetdb.dir/tools/resetdb.c.i
.PHONY : tools/resetdb.c.i

tools/resetdb.s: tools/resetdb.c.s
.PHONY : tools/resetdb.s

# target to generate assembly for a file
tools/resetdb.c.s:
	$(MAKE) -f CMakeFiles/resetdb.dir/build.make CMakeFiles/resetdb.dir/tools/resetdb.c.s
.PHONY : tools/resetdb.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... db_test"
	@echo "... director"
	@echo "... edit_cache"
	@echo "... improveesation_communication"
	@echo "... improveesation_db"
	@echo "... musician"
	@echo "... player"
	@echo "... rebuild_cache"
	@echo "... resetdb"
	@echo "... core/communication.o"
	@echo "... core/communication.i"
	@echo "... core/communication.s"
	@echo "... core/configuration.o"
	@echo "... core/configuration.i"
	@echo "... core/configuration.s"
	@echo "... core/db.o"
	@echo "... core/db.i"
	@echo "... core/db.s"
	@echo "... core/db_library_test.o"
	@echo "... core/db_library_test.i"
	@echo "... core/db_library_test.s"
	@echo "... core/director_core.o"
	@echo "... core/director_core.i"
	@echo "... core/director_core.s"
	@echo "... core/director_main.o"
	@echo "... core/director_main.i"
	@echo "... core/director_main.s"
	@echo "... core/musician_core.o"
	@echo "... core/musician_core.i"
	@echo "... core/musician_core.s"
	@echo "... core/musician_improviser.o"
	@echo "... core/musician_improviser.i"
	@echo "... core/musician_improviser.s"
	@echo "... core/musician_main.o"
	@echo "... core/musician_main.i"
	@echo "... core/musician_main.s"
	@echo "... core/player_core.o"
	@echo "... core/player_core.i"
	@echo "... core/player_core.s"
	@echo "... core/player_main.o"
	@echo "... core/player_main.i"
	@echo "... core/player_main.s"
	@echo "... core/utils.o"
	@echo "... core/utils.i"
	@echo "... core/utils.s"
	@echo "... tools/resetdb.o"
	@echo "... tools/resetdb.i"
	@echo "... tools/resetdb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

